### ISSUE TITLE
README: should mention install alternative - without adding the gem to the Gemfile

### ISSUE THREAD

**Issue by paulwittmann** [railslove/fontello_rails_converter#15]
fontelloe_rails_converter shouldn't be a dependency of my app, best make people aware that the can use it without adding it to their Gemfile.

**Comment by jaredbeck** [comment]
Or at least put it in `group :development`, right?  The important thing is that it's not needed in memory in production, right?

**Comment by jhilden** [comment]
I added a note to the README:  https://github.com/railslove/fontello_rails_converter/blob/master/README.md#gemfile-enviroment

Does that clear things up?  Feedback is welcome.

**Comment by jaredbeck** [comment]
> If you don't want to load this gem in your app's production environment to save a tiny bit of memory ..

I don't want to hijack Paul's thread here, which is about removing it from the Gemfile entirely.  I think he may have simply wanted fewer dependencies to maintain.  I can relate.  @paulwittmann, is that right?  Can you share your experience after removing it entirely?  Did you need to do any configuration?

>> it's not needed in memory in production, right?
>
> .. you might need to change is to tell rails to add vendor/assets/fonts to the precompile load paths ..

That's good to know, thanks!

**Comment by paulwittmann** [comment]
i'm fine with group development. thanks for your feedback, Jared!
