### ISSUE TITLE
zsh: command not found: fontello

### ISSUE THREAD

**Issue by rootical** [railslove/fontello_rails_converter#21]
Hi, thank you for your work. The issue looks similar to #13. I have 0.3.2 version installed and use zsh.
Shall i add it manually to path? 
By the way, bundle exec fontello convert works

**Comment by ka8725** [comment]
@rootical , you have to put he `fontello` program into bundled commands in zsh. To do this follow the steps:

1. Update bundler plugin of zsh: `cd ~/.oh-my-zsh/plugins/bundler && git fetch origin && git rebase origin/master`. I'm not sure which version of the plugin do you have, but if yo have an older version than this [commit](https://github.com/robbyrussell/oh-my-zsh/commit/4b997429b3785aefa929732d7dbf431e7884bc4d) the following steps won't make regarding effect.
2. `open ~/.zshrc`
3. Add this line into the file: `BUNDLED_COMMANDS=(fontello)`
4. Restart the shell: `exec $SHELL` or just reload the terminal
5. Go to the project with installed `fontello_rails_converter` gem and now you are free to use `fontello open` command

**Comment by ka8725** [comment]
Opened pull request for guys from `zsh`: https://github.com/robbyrussell/oh-my-zsh/pull/3679

**Comment by jhilden** [comment]
closing this, because there has been no new acitivity
