### ISSUE TITLE
Rails says: Extra .css in SCSS file is unnecessary.

### ISSUE THREAD

**Issue by adekbadek** [railslove/fontello_rails_converter#26]
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename  (...)/vendor/assets/stylesheets/fontello.css.scss to (...)/vendor/assets/stylesheets/fontello.scss.

**Comment by jhilden** [comment]
Thanks for reporting that issue @adekbadek 

Could you check if you issue is fixed by fc5e57751122182ee35bad058d9b633af6311800 ?

**Comment by adekbadek** [comment]
Yes, the issue is fixed now, thanks!

**Comment by jhilden** [comment]
Thanks for the feedback about the fix.  I released a new version `0.3.3`
