### ISSUE TITLE
Fontello demo failed

### ISSUE THREAD

**Issue by ka8725** [railslove/fontello_rails_converter#27]
![2015-05-21 at 4 17](https://cloud.githubusercontent.com/assets/243846/7739800/55b94d8e-ff70-11e4-9c4d-da3e061ed7c1.png)

**Comment by jhilden** [comment]
I think I might have seen a similar result and it had to do with the character encoding (in the CSS i think).

But in any case we would need much more information to help and ideally a test app to reproduce this bug.

**Comment by cimm** [comment]
Same problem here, what was the character encoding problem and how do we fix it?

**Comment by ka8725** [comment]
I think that the problem in incorrect path to the assets files.

**Comment by jhilden** [comment]
If you could at least provide some additional information about your setup (rails & ruby versions, asset paths, etc.) maybe we can diagnose this further, otherwise it's all just guesswork.

The ideal thing would be a minimal rails test app that reproduces the problem.

**Comment by doppelreim** [comment]
In this fontello-issue https://github.com/fontello/fontello/issues/382 some CSS was inlined into the original demo.html (see https://github.com/fontello/fontello/commit/1d9ba71ef30902005351dafa56d6da9038132cee).
The URLs in the inlined ```@font-face``` are not converted for the asset-pipeline.

I suspect https://github.com/railslove/fontello_rails_converter/blob/master/lib/fontello_rails_converter/cli.rb#L128 would need to bee amended?

**Comment by jpwhitaker** [comment]
I had the same issue, was very confused until I tried using an icon myself rather than looking at the demo.

Icons work, demo is not working.

Rails: 4.1.6
Ruby: 2.2.0

**Comment by jhilden** [comment]
I merged @doppelreim's PR and released a new version `0.4.0`.  Let me know if it works for you and fixes your issues with the fontello demo.

**Comment by doppelreim** [comment]
Cool! The fontello-demo is now working for me.

**Comment by jhilden** [comment]
thanks for verifying the bugfix
