### ISSUE TITLE
No implicit conversion of Nil into String when running fontello convert

### ISSUE THREAD

**Issue by wizzor** [railslove/fontello_rails_converter#29]
Error message reads:

/home/visa/.rvm/gems/ruby-2.2.1/gems/fontello_rails_converter-0.4.0/lib/fontello_rails_converter/cli.rb:77:in `read': no implicit conversion of nil into String (TypeError)
	from /home/visa/.rvm/gems/ruby-2.2.1/gems/fontello_rails_converter-0.4.0/lib/fontello_rails_converter/cli.rb:77:in `convert_main_stylesheet'
	from /home/visa/.rvm/gems/ruby-2.2.1/gems/fontello_rails_converter-0.4.0/lib/fontello_rails_converter/cli.rb:62:in `convert'
	from /home/visa/.rvm/gems/ruby-2.2.1/gems/fontello_rails_converter-0.4.0/bin/fontello:134:in `<top (required)>'
	from /home/visa/.rvm/gems/ruby-2.2.1/bin/fontello:23:in `load'
	from /home/visa/.rvm/gems/ruby-2.2.1/bin/fontello:23:in `<main>'
	from /home/visa/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/visa/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

For some reason the various fontello_name variables seem to be passed in as empty.

Env: RVM, Rails 4.1.6

Edit: Installed via Bundler + Gemfile

**Comment by jhilden** [comment]
Thanks for the bug report @wizzor 

Could you provide some more information in what context the bug appeared?
* Was it initial usage of the gem or were you updateing an existing fontello font?
* What is the exact command in which folder that is failing?
* Where is you `config.json` located and what is it's content?  Especially asking for the `"name"` property in there.

The best thing for me to fix the bug would be some concrete steps to reproduce the issue.

I hope you can help me out with fixing this.

**Comment by wizzor** [comment]
Of course,
This was initial usage, I downloaded a Fontello zip, renamed it to fontello.zip, placed in app's /tmp directory
Command used was 
    fontello convert --no-download
The config.json is inside the fontello-generated zip file, and gets correctly copied over to ./vendor/assets/fonts/config.json

The name value is empty, as I didn't specify a name for Fontello. I will retry with a named fontello font and report back.

**Comment by wizzor** [comment]
Hi,
The process completed successfully after I gave a name to the font package.

As an improvement suggestion, I propose one of the following:
- Set a default name to be used eg. fontello-rc
- Raise an error with instructions to re-generate the font package with a name specified, if none is found

**Comment by ka8725** [comment]
@wizzor , how did you give the font package name? If manually change the `config.json` it will be deleted after running the `fontello convert` command.

**Comment by wizzor** [comment]
I renamed the package in fontello UI, saved and redownloaded the package,
and then ran fontello convert --no-download again, everything works well
now.
