### ISSUE TITLE
Convert additional fontello stylesheets?

### ISSUE THREAD

**Issue by dlackty** [railslove/fontello_rails_converter#32]
Currently only the main stylesheet get converted and I thought that others should get converted as well?

**Comment by jhilden** [comment]
Hi @dlackty,

FYI:  I added a bit of documentation to the README about what exactly is done during the conversion:  https://github.com/railslove/fontello_rails_converter/blob/master/README.md#sass-enhacements

For which stylesheets exactly do you think a conversion would be necessary/useful?

**Comment by dlackty** [comment]
I thought the main reason for converting stylesheets if for sprockets asset loading? In this case, `fontname-embedded.css` might also be converted.

**Comment by jhilden** [comment]
I changed master, so that the embedded stylesheet will also be converted.   It would be nice if you could try it out and report if it works as expected.

**Comment by jhilden** [comment]
I just released version `0.4.2` which should fix this issue.
