### ISSUE TITLE
Icons all mixed up

### ISSUE THREAD

**Issue by EddieOne** [railslove/fontello_rails_converter#35]
Hi,

Someone installed fontello_rails_converter on the project I work in some time ago. The config.json was missing. I tried to import the svg I have into fontello.com. Everything seems alright except the icons are mixed up in the project. Seems each time I try to do it, the icons are mixed differently. Is there any hope to fix this? If so, how can it be done?

**Comment by jhilden** [comment]
Hi @EddieOne thanks for your report.  Could you provide some additional information and the exact steps how to reproduce the behavior you are describing?

**Comment by EddieOne** [comment]
Hi, @jhilden, I took the the fontello.svg from my project, dragged it into fontello.com, downloaded the zip, placed it at myapp/tmp/fontello.zip, and run the command 'fontello convert --no-download'.

**Comment by jhilden** [comment]
Did it persist a `config.json`?  Was that config.json used for subsequent `fontello` calls?

**Comment by EddieOne** [comment]
The project is old, like 10 years old. I searched the git history and it seems there was never a config.json. This was my attempt to create one from the svg font file.

It seems someone no longer working on the project, once install fontello_rails_converter and forgot to put the config.json in place.

**Comment by EddieOne** [comment]
hmm I tried this again and it seems to work now. I'm going to pretend I'm sure it was v0.4.2 that fixed it as I have no idea otherwise. Thanks
