### ISSUE TITLE
WOFF2 Support

### ISSUE THREAD

**Issue by chriszamierowski** [railslove/fontello_rails_converter#40]
It looks like Fontello [now supports WOFF2](https://github.com/fontello/fontello/commit/ad9614189c46506877763611f3ce2004d280276e), so running `fontello convert` results in a .scss file that looks something like:
```
@font-face {
  font-family: 'fontname';
  src: font-url('fontname.eot?36722241');
  src: font-url('fontname.eot?36722241#iefix') format('embedded-opentype'),
       font-url('fontname.woff2?36722241') format('woff2'),
       font-url('fontname.woff?36722241') format('woff'),
       font-url('fontname.ttf?36722241') format('truetype'),
       font-url('fontname.svg?36722241#fontname') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
The issue is the actual .woff2 font file isn't downloading with it. I've got a (very simple) fix [here](https://github.com/chriszamierowski/fontello_rails_converter/commit/d2748e05fbab160950d280c1736d173ccd092b11), but I'm not sure how to provide test coverage for this (or if it even needs it).

If somebody can walk me through that I'd be happy to submit a PR

**Comment by jhilden** [comment]
thanks for reporting this.  I would say definitely make a PR for this and we will see if there are any failing tests or if additional tests should be written.  But it looks simple enough to me.
