### ISSUE TITLE
can't find executable fontello for gem fontello_rails_converter (Gem::Exception)

### ISSUE THREAD

**Issue by duleorlovic** [railslove/fontello_rails_converter#47]
I'm getting following error when I try to use it in command line
```
bundle exec fontello convert
```

I have it in Gemfile
```
# Gemfile
gem 'fontello_rails_converter'
```

**Comment by duleorlovic** [comment]
One workaround is to use
```
gem which fontello_rails_converter

```

and than use full path
```
/home/orlovic/.rvm/gems/ruby-2.6.3/gems/fontello_rails_converter-0.4.6/bin/fontello  convert
```

**Comment by bumi** [comment]
Hi @duleorlovic 
do other commands from other rubygems work within your project?
are you sure your PATH environment variable is configured to find the executable within the rvm directories?

**Comment by duleorlovic** [comment]
Yea, that was a problem... rvm did not catch up all my PATHS (not sure why, but now it works).
Thanks @bumi
